apiVersion: v2
name: servarr
description: Servarr complete Helm Chart for Kubernetes
type: application
version: 1.0.2
appVersion: "1.0.2"
keywords:
  - servarr
  - prowlarr
  - radarr
  - sonarr
  - bazarr
  - qbittorrent
  - jellyseerr
  - jellyfin
  - flaresolverr
home: https://github.com/fonzdm/servarr
sources:
  - https://github.com/fonzdm/servarr
dependencies:
  - name: sonarr
    version: "25.0.1"
    repository: "oci://tccr.io/truecharts"
  - name: radarr
    version: "26.0.0"
    repository: "oci://tccr.io/truecharts"
  - name: bazarr
    version: "23.0.0"
    repository: "oci://tccr.io/truecharts"
  - name: prowlarr
    version: "21.0.0"
    repository: "oci://tccr.io/truecharts"
  - name: qbittorrent
    version: "24.0.0"
    repository: "oci://tccr.io/truecharts"
  - name: jellyseerr
    version: "13.11.3"
    repository: "oci://tccr.io/truecharts"
  - name: jellyfin
    version: "21.12.6"
    repository: "oci://tccr.io/truecharts"
  - name: flaresolverr
    version: "16.12.5"
    repository: "oci://tccr.io/truecharts"

maintainers:
  - name: Alfonso De Masi
    email: adm220297@proton.me
