{{- if .Values.qbittorrent.addons.gluetun.enabled }}
# Gluetun control server service for VPN status monitoring
# Exposes the gluetun HTTP control server internally for homepage widget
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-qbittorrent-gluetun
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: qbittorrent-gluetun
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: qbittorrent
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: gluetun
      port: 8000
      targetPort: 8000
      protocol: TCP
{{- end }}
