apiVersion: batch/v1
kind: Job
metadata:
  name: jellyfin-init
  labels:
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "30"
spec:
  backoffLimit: 1
  template:
    metadata:
      name: "{{.Release.Name}}-jellyfin-finalizer"
      labels:
        app: "{{ .Release.Name }}"
    spec:
      restartPolicy: Never
      {{- with .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: wait-for-jellyfin
          image: curlimages/curl:8.7.1
          imagePullPolicy: IfNotPresent
          command:
            [
              "sh",
              "-c",
              "until curl  \"http://{{ .Release.Name }}-jellyfin.{{ .Release.Namespace }}.svc.cluster.local:8096\"; do echo waiting for servarr-jellyfin; sleep 5; done;sleep 10;",
            ]
      containers:
      - name: initialize-jellyfin
        image: "python:3.11-alpine"
        imagePullPolicy: IfNotPresent
        env:
          - name: PYTHONUNBUFFERED
            value: "1"
          - name: JELLYFIN_HOST
            value: "{{ .Release.Name }}-jellyfin.{{ .Release.Namespace }}.svc.cluster.local:8096"
          - name: JELLYFIN_USERNAME
            value: "{{ $.Values.global.username }}"
          - name: JELLYFIN_PASSWORD
            value: "{{ $.Values.global.password }}"
          - name: COUNTRY_CODE
            value: "{{ $.Values.global.countryCode }}"
          - name: PREFERRED_LANGUAGE
            value: "{{ $.Values.global.preferredLanguage }}"
          - name: JELLYFIN_TRANSCODER_ENABLED
            value: {{ default false $.Values.jellyfin.persistence.transcode.enabled | quote }}
          - name: JELLYFIN_TRANSCODER_BODY_FILE
            value: "/config/jellyfin-transcoder-body.json"
        command:
          - "/bin/sh"
          - "-ec"
        args:
          - "python3 -m pip install --no-cache-dir requests >/dev/null 2>&1 && python3 -u /mnt/init-jellyfin.py 2>&1;"
        volumeMounts:
          - mountPath: "/mnt"
            name: python-script
          - mountPath: "/config"
            name: jellyfin-config
{{- if and $.Values.jellyfin.transcoder $.Values.jellyfin.transcoder.body }}
          - mountPath: "/config/jellyfin-transcoder-body.json"
            name: python-script
            subPath: jellyfin-transcoder-body.json
{{- end }}
      volumes:
        - name: python-script
          configMap:
            name: init-jellyfin-script
        - name: jellyfin-config
          persistentVolumeClaim:
            claimName: {{ printf "%s-jellyfin-config" .Release.Name }}
