{{- range $key := list "downloads" "media" "torrentConfig" }}
{{- $volume := index $.Values.volumes $key }}
{{- if and $volume.enabled (not (lookup "v1" "PersistentVolumeClaim" $.Release.Namespace $volume.name)) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $volume.name }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/resource-policy: keep
spec:
  storageClassName: {{ $.Values.volumes.storageClass | quote }}
  accessModes:
    {{- toYaml $.Values.volumes.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ $volume.size }}
---
{{- end }}
{{- end }}
